server:
  port: 6502
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shop_oms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: hou2021
  application:
    name: shops-order
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto





