server:
  port: 7809
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: hou2021
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    application:
      name: shop-email
  mail:
    #smtp服务主机  qq邮箱则为smtp.qq.com
    host: smtp.163.com
    #服务协议
    protocol: smtp
    # 编码集
    default-encoding: UTF-8
    #发送邮件的账户
    username: 18039317141@163.com
    #授权码
    password: GOQAOIUWMRDTGHYD
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true






