server:
  port: 6501
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shop_pms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: hou2021
  application:
    name: shops-product
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500
        min-idle: 0
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
thymeleaf:
  cache: false
  suffix: .html
  prefix: classpath:/templates/




